// ════════════════════════════════════════════════════
//  PROGRAM VERİSİ — Kırşehir Ahi Evran Üniversitesi 1. YZ Günleri
//  04–06 Mayıs 2026 · Mucur MYO
// ════════════════════════════════════════════════════

export const GUN1 = [
  {
    id: 'g1-1',
    time: '08:30–09:00',
    duration: '30 dk',
    type: 'arasol',
    typeLabel: 'Lojistik',
    title: 'Kayıt ve Karşılama',
    location: 'Giriş Holü',
    desc: 'Katılımcı kaydı, isim kartı ve doküman dağıtımı',
  },
  {
    id: 'g1-2',
    time: '09:00–09:30',
    duration: '30 dk',
    type: 'opening',
    typeLabel: 'Tören',
    title: 'Açılış Töreni',
    location: 'Konferans Salonu',
    desc: 'İstiklal Marşı, saygı duruşu, protokol fotoğrafı',
    highlight: true,
  },
  {
    id: 'g1-3',
    time: '09:30–10:00',
    duration: '30 dk',
    type: 'konusma',
    typeLabel: 'Konuşma',
    title: 'Rektör / Rektör Yrd. Açılış Konuşması',
    location: 'Konferans Salonu',
    desc: 'YZ ve mesleki eğitimde Kırşehir Ahi Evran Üniversitesi\'nin vizyonu',
    speaker: 'Rektörlük — KAEU',
    highlight: true,
  },
  {
    id: 'g1-4',
    time: '10:00–10:20',
    duration: '20 dk',
    type: 'konusma',
    typeLabel: 'Konuşma',
    title: 'MYO Müdürü Konuşması',
    location: 'Konferans Salonu',
    desc: 'Mucur MYO\'nun 9 bölüm bazında YZ stratejisi',
    speaker: 'MYO Müdürü',
  },
  {
    id: 'g1-5',
    time: '10:20–10:40',
    duration: '20 dk',
    type: 'konusma',
    typeLabel: 'Paydaş Konuşması',
    title: 'İlçe Kaymakamı Konuşması',
    location: 'Konferans Salonu',
    desc: 'Bölgesel kalkınmada ve Mucur ilçesinin geleceğinde yapay Zekânın rolü',
    speaker: 'Mucur Kaymakamlığı',
    highlight: true,
  },
  {
    id: 'g1-6',
    time: '10:40–11:00',
    duration: '20 dk',
    type: 'konusma',
    typeLabel: 'Konuşma',
    title: 'Yapay Zekâ ve Sağlık Çalışmaları',
    location: 'Konferans Salonu',
    desc: 'Yapay Zekâ ve sağlık çalışmaları üzerine sunum',
    speaker: 'Prof. Dr. Ufuk KARADAVUT',
    highlight: true,
  },
  {
    id: 'g1-7',
    time: '10:40–11:00',
    duration: '20 dk',
    type: 'arasol',
    typeLabel: 'Ara',
    title: 'Kahve Molası ve Networking',
    location: 'Fuaye',
  },
  {
    id: 'g1-8',
    time: '11:00–12:30',
    duration: '90 dk',
    type: 'panel',
    typeLabel: 'Panel',
    title: 'Panel: Yapay Zekâ — Bugünü ve Yarını',
    location: 'Konferans Salonu',
    desc: 'Yapay Zekânın eğitim, sanayi, tarım ve kamu sektöründeki dönüştürücü etkisi; Türkiye\'nin AI vizyonu',
    speaker: 'Prof. Dr. Murat ÇANLI (Moderatör)',
    highlight: true,
  },
  {
    id: 'g1-9',
    time: '12:30–13:30',
    duration: '60 dk',
    type: 'arasol',
    typeLabel: 'Mola',
    title: 'Öğle Yemeği',
    location: 'Yemekhane',
  },
  {
    id: 'g1-10',
    time: '13:30–15:00',
    duration: '90 dk',
    type: 'panel',
    typeLabel: 'Panel',
    title: 'Panel: Akademide Yapay Zekâ',
    location: 'Konferans Salonu',
    desc: 'Yapay Zekânın akademik hayatta kullanımı — muhasebe, eğitim, sağlık ve etik boyutları',
    speaker: 'Dr. Öğr. Üyesi Fatma KESKİNKILIÇ (Moderatör)',
    highlight: true,
  },
  {
    id: 'g1-11',
    time: '15:00–15:15',
    duration: '15 dk',
    type: 'arasol',
    typeLabel: 'Ara',
    title: 'Kısa Mola',
  },
  {
    id: 'g1-12',
    time: '15:15–17:00',
    duration: '105 dk',
    type: 'konusma',
    typeLabel: 'Eğitim',
    title: 'Yapay Zekâ ile İçerik Üretimi',
    location: 'Konferans Salonu',
    desc: 'Yapay zekâ araçlarıyla içerik üretimi üzerine uygulamalı eğitim',
    speaker: 'Doç. Dr. Yusuf Ziya OLPAK',
    highlight: true,
  },
];

// ════════════════════════════════════════════════════
//  2. GÜN — Workshop (Salon A-B-C-D)
// ════════════════════════════════════════════════════

export const GUN2_WORKSHOP = [
  {
    id: 'g2w-1',
    time: '08:30–09:00',
    duration: '30 dk',
    type: 'arasol',
    typeLabel: 'Lojistik',
    title: 'Katılımcı Karşılama & Salon Yönlendirme',
    location: 'Giriş Holü',
    desc: 'Workshop salonlarına yönlendirme ve salon görevlilerinin hazırlık kontrolü',
  },
  {
    id: 'g2w-2',
    time: '09:00–10:30',
    duration: '90 dk',
    type: 'workshop',
    typeLabel: 'Workshop Oturumu 1',
    title: 'Workshop Oturumu 1 (Salon A-B-C-D)',
    location: 'Salon A-B-C-D',
    desc: 'Paralel workshop seansları — her salon kendi konusunda çalışır',
    speaker: 'Salon Yürütücüleri',
    highlight: true,
  },
  {
    id: 'g2w-3',
    time: '10:45–12:30',
    duration: '90 dk',
    type: 'workshop',
    typeLabel: 'Workshop Oturumu 2',
    title: 'Workshop Oturumu 2 (Salon A-B-C-D)',
    location: 'Salon A-B-C-D',
    desc: 'Paralel workshop seansları devamı',
    speaker: 'Salon Yürütücüleri',
    highlight: true,
  },
  {
    id: 'g2w-4',
    time: '12:30–13:30',
    duration: '60 dk',
    type: 'arasol',
    typeLabel: 'Mola',
    title: 'Öğle Yemeği',
    location: 'Yemekhane',
  },
  {
    id: 'g2w-5',
    time: '13:30–15:00',
    duration: '90 dk',
    type: 'workshop',
    typeLabel: 'Workshop Oturumu 3',
    title: 'Workshop Oturumu 3 (Salon A-B-C-D)',
    location: 'Salon A-B-C-D',
    desc: 'Paralel workshop seansları devamı',
    speaker: 'Salon Yürütücüleri',
    highlight: true,
  },
  {
    id: 'g2w-6',
    time: '15:15–17:00',
    duration: '105 dk',
    type: 'workshop',
    typeLabel: 'Workshop Oturumu 4',
    title: 'Workshop Oturumu 4 (Salon A-B-C-D)',
    location: 'Salon A-B-C-D',
    desc: 'Paralel workshop seansları — son blok',
    speaker: 'Salon Yürütücüleri',
    highlight: true,
  },
];

// ════════════════════════════════════════════════════
//  2. GÜN — Workshop Salon Detayları
// ════════════════════════════════════════════════════

export const WORKSHOP_DETAY = [
  { sira: 1, salon: 'A-B-C-D', bolum: 'UZEM', konu: 'Eğitimde Prompt Mühendisliği', yurutucu: 'Doç. Dr. Uğur BAŞARMAK' },
  { sira: 2, salon: 'A-B-C-D', bolum: 'UZEM', konu: 'Eğitimde Yapay Zekâ Tabanlı İçerik Üretimi', yurutucu: 'Doç. Dr. Uğur BAŞARMAK' },
  { sira: 3, salon: 'A-B-C-D', bolum: 'UZEM', konu: 'Yapay Zekâ ile Sosyal Medya İçerik Tasarımı: Canva Atölyesi', yurutucu: 'Öğr. Gör. Tuğçe Bölükbaş' },
  { sira: 4, salon: 'A-B-C-D', bolum: 'Bilgisayar Teknolojileri Bölümü', konu: 'FIGMA', yurutucu: 'Öğr. Gör. Murat GÜZEL / Dr. Öğr. Üyesi Şaban FINDIK' },
  { sira: 5, salon: 'A-B-C-D', bolum: 'Bilgisayar Teknolojileri Bölümü', konu: 'Claude / Gemini / ChatGPT', yurutucu: 'Öğr. Gör. Murat GÜZEL / Dr. Öğr. Üyesi Şaban FINDIK' },
  { sira: 6, salon: 'A-B-C-D', bolum: 'Bilgisayar Teknolojileri Bölümü', konu: 'NotebookLM', yurutucu: 'Öğr. Gör. Ahmet Burak ÖZKAN / Öğr. Gör. Hüsnü KARADAĞ' },
  { sira: 7, salon: 'A-B-C-D', bolum: 'Bilgisayar Teknolojileri Bölümü', konu: 'AntiGravity', yurutucu: 'Öğr. Gör. Ahmet Burak ÖZKAN / Öğr. Gör. Hüsnü KARADAĞ' },
  { sira: 8, salon: 'A-B-C-D', bolum: 'Bilgisayar Teknolojileri Bölümü', konu: 'Oyun Programlama', yurutucu: 'Öğr. Gör. İlker SEZER / Öğr. Gör. Barış Safa GÜRLER' },
  { sira: 9, salon: 'A-B-C-D', bolum: 'Bilgisayar Teknolojileri Bölümü', konu: '2D Animasyon', yurutucu: 'Öğr. Gör. İlker SEZER / Öğr. Gör. Barış Safa GÜRLER' },
  { sira: 10, salon: 'A-B-C-D', bolum: 'Bankacılık, Sigortacılık ve Finans Bölümü', konu: 'Warren AI', yurutucu: 'Dr. Öğr. Üyesi Mücahit ÜLGER' },
  { sira: 11, salon: 'A-B-C-D', bolum: 'Tasarım', konu: 'Tasarımda YZ Araçları', yurutucu: 'Öğr. Gör. Sezin NİKBAY' },
  { sira: 12, salon: 'A-B-C-D', bolum: 'Görsel İletişim', konu: 'NanoBanana', yurutucu: 'Öğr. Gör. Dr. Ali KAYMAK' },
];

// ════════════════════════════════════════════════════
//  2. GÜN — Konferans (Konferans Salonu)
// ════════════════════════════════════════════════════

export const GUN2_KONFERANS = [
  {
    id: 'g2k-1',
    time: '08:30–09:00',
    duration: '30 dk',
    type: 'arasol',
    typeLabel: 'Lojistik',
    title: 'Katılımcı Karşılama & Salon Yönlendirme',
    location: 'Giriş Holü',
    desc: 'Workshop salonlarına yönlendirme ve salon görevlilerinin hazırlık kontrolü',
  },
  {
    id: 'g2k-2',
    time: '09:00–09:20',
    duration: '20 dk',
    type: 'konusma',
    typeLabel: 'Konuşma (Sunum)',
    title: 'YZ Destekli İnsansız Hava Araçları: İHA ile Hassas Tarım Uygulamaları',
    location: 'Konferans Salonu',
    desc: 'Yapay Zekâ destekli insansız hava araçları ile hassas tarım uygulamaları',
    speaker: 'Dr. Öğr. Üyesi Veysel GÜL',
    highlight: true,
  },
  {
    id: 'g2k-3',
    time: '09:30–09:50',
    duration: '20 dk',
    type: 'konusma',
    typeLabel: 'Konuşma (Sunum)',
    title: 'Tarımsal Üretimde Yapay Zekânın Rolü',
    location: 'Konferans Salonu',
    desc: 'Tarımsal üretimde yapay Zekânın rolü üzerine sunum',
    speaker: 'Dr. Öğr. Üyesi Gülden ÖZGÜNALTAY ERTUĞRUL',
    highlight: true,
  },
  {
    id: 'g2k-4',
    time: '10:00–10:20',
    duration: '20 dk',
    type: 'konusma',
    typeLabel: 'Konuşma (Sunum)',
    title: 'Konuşma (Sunum)',
    location: 'Konferans Salonu',
    desc: 'Konuşmacı belirlenecek',
  },
  {
    id: 'g2k-5',
    time: '10:30–10:50',
    duration: '20 dk',
    type: 'konusma',
    typeLabel: 'Konuşma (Sunum)',
    title: 'Konuşma (Sunum)',
    location: 'Konferans Salonu',
    desc: 'Konuşmacı belirlenecek',
  },
  {
    id: 'g2k-6',
    time: '11:00–11:20',
    duration: '20 dk',
    type: 'konusma',
    typeLabel: 'Konuşma (Sunum)',
    title: 'Konuşma (Sunum)',
    location: 'Konferans Salonu',
    desc: 'Konuşmacı belirlenecek',
  },
  {
    id: 'g2k-7',
    time: '11:30–11:50',
    duration: '20 dk',
    type: 'konusma',
    typeLabel: 'Konuşma (Sunum)',
    title: 'Yapay Zekânın Matematiksel Temelleri',
    location: 'Konferans Salonu',
    desc: 'Yapay Zekânın matematiksel temelleri üzerine sunum',
    speaker: 'Prof. Dr. Cahit AYTEKİN',
    highlight: true,
  },
  {
    id: 'g2k-8',
    time: '12:00–12:20',
    duration: '20 dk',
    type: 'konusma',
    typeLabel: 'Konuşma (Sunum)',
    title: 'Yapay Zekânın Çalışma Hayatına Etkileri',
    location: 'Konferans Salonu',
    desc: 'Yapay Zekânın çalışma hayatına etkileri üzerine sunum',
    speaker: 'SGK Kırşehir İl Müdürü / H. Hüseyin ŞENLİK',
    highlight: true,
  },
  {
    id: 'g2k-9',
    time: '12:20–12:30',
    duration: '10 dk',
    type: 'konusma',
    typeLabel: 'Değerlendirme',
    title: 'Değerlendirme',
    location: 'Konferans Salonu',
  },
  {
    id: 'g2k-10',
    time: '12:30–13:30',
    duration: '60 dk',
    type: 'arasol',
    typeLabel: 'Öğle Arası',
    title: 'Öğle Arası',
    location: 'Yemekhane',
  },
  {
    id: 'g2k-11',
    time: '13:30–13:50',
    duration: '20 dk',
    type: 'konusma',
    typeLabel: 'Konuşma (Sunum)',
    title: 'Yapay Zekânın Muhasebe Mesleğine Etkisi',
    location: 'Konferans Salonu',
    desc: 'Yapay Zekânın muhasebe mesleğine etkisi üzerine sunum',
    speaker: 'SMMM Kırşehir Başkanı / Ziya Anıl MEMİŞ',
    highlight: true,
  },
  {
    id: 'g2k-12',
    time: '14:00–14:20',
    duration: '20 dk',
    type: 'konusma',
    typeLabel: 'Konuşma (Sunum)',
    title: 'Çağımızın Yaratıcı Yıkım Süreci ve Yapay Zekâ',
    location: 'Konferans Salonu',
    desc: 'Çağımızın yaratıcı yıkım süreci ve yapay Zekâ üzerine sunum',
    speaker: 'Azupir / Doç. Dr. Çağrı SEL, Dr. Öğr. Üyesi Tuğrul BAYRAKTAR',
    highlight: true,
  },
  {
    id: 'g2k-13',
    time: '14:30–14:50',
    duration: '20 dk',
    type: 'konusma',
    typeLabel: 'Konuşma (Sunum)',
    title: 'Çağrı Merkezlerinde Yapay Zekâ Kullanımı',
    location: 'Konferans Salonu',
    desc: 'Çağrı merkezlerinde yapay Zekâ kullanımı üzerine sunum',
    speaker: 'Megadentist / Hasan Hüseyin SAVUKDURAN',
    highlight: true,
  },
  {
    id: 'g2k-14',
    time: '15:00–15:20',
    duration: '20 dk',
    type: 'konusma',
    typeLabel: 'Konuşma (Sunum)',
    title: 'YZ ile Beslenmenin Geleceği: Kişiselleştirilmiş Sağlıkta Yeni Dönem',
    location: 'Konferans Salonu',
    desc: 'Yapay Zekâ ile beslenmenin geleceği ve kişiselleştirilmiş sağlıkta yeni dönem',
    speaker: 'Dyt. Kübra SARI',
    highlight: true,
  },
  {
    id: 'g2k-15',
    time: '15:30–15:50',
    duration: '20 dk',
    type: 'konusma',
    typeLabel: 'Konuşma (Sunum)',
    title: 'Konuşma (Sunum)',
    location: 'Konferans Salonu',
    desc: 'Konuşmacı belirlenecek',
  },
  {
    id: 'g2k-16',
    time: '16:00–16:20',
    duration: '20 dk',
    type: 'konusma',
    typeLabel: 'Konuşma (Sunum)',
    title: 'YZ ve YZ Destekli Öğrenme Deneyimleri',
    location: 'Konferans Salonu',
    desc: 'Yapay Zekâ ve yapay Zekâ destekli öğrenme deneyimleri',
    speaker: 'Madlen.io',
    highlight: true,
  },
  {
    id: 'g2k-17',
    time: '16:30–16:50',
    duration: '20 dk',
    type: 'konusma',
    typeLabel: 'Konuşma (Sunum)',
    title: 'Konuşma (Sunum)',
    location: 'Konferans Salonu',
    desc: 'Konuşmacı belirlenecek',
  },
  {
    id: 'g2k-18',
    time: '16:50–17:00',
    duration: '10 dk',
    type: 'opening',
    typeLabel: 'Kapanış',
    title: 'Kapanış',
    location: 'Konferans Salonu',
  },
];

// ════════════════════════════════════════════════════
//  3. GÜN — Bildiri Sunumları (Salon 1)
// ════════════════════════════════════════════════════

export const GUN3_BILDIRI = [
  {
    id: 'g3b-1',
    time: '08:30–09:00',
    duration: '30 dk',
    type: 'arasol',
    typeLabel: 'Lojistik',
    title: 'Katılımcı Karşılama & Salon Yönlendirme',
    location: 'Giriş Holü',
    desc: 'Salon görevlilerinin hazırlık kontrolü',
  },
  {
    id: 'g3b-2', time: '09:00–09:20', duration: '20 dk', type: 'konusma', typeLabel: 'Bildiri (Sunum)',
    title: 'Bildiri Sunumu', location: 'Salon 1', desc: 'Bildiri sunumu — konuşmacı belirlenecek',
  },
  {
    id: 'g3b-3', time: '09:30–09:50', duration: '20 dk', type: 'konusma', typeLabel: 'Bildiri (Sunum)',
    title: 'Bildiri Sunumu', location: 'Salon 1', desc: 'Bildiri sunumu — konuşmacı belirlenecek',
  },
  {
    id: 'g3b-4', time: '10:00–10:20', duration: '20 dk', type: 'konusma', typeLabel: 'Bildiri (Sunum)',
    title: 'Bildiri Sunumu', location: 'Salon 1', desc: 'Bildiri sunumu — konuşmacı belirlenecek',
  },
  {
    id: 'g3b-5', time: '10:30–10:50', duration: '20 dk', type: 'konusma', typeLabel: 'Bildiri (Sunum)',
    title: 'Bildiri Sunumu', location: 'Salon 1', desc: 'Bildiri sunumu — konuşmacı belirlenecek',
  },
  {
    id: 'g3b-6', time: '11:00–11:20', duration: '20 dk', type: 'konusma', typeLabel: 'Bildiri (Sunum)',
    title: 'Bildiri Sunumu', location: 'Salon 1', desc: 'Bildiri sunumu — konuşmacı belirlenecek',
  },
  {
    id: 'g3b-7', time: '11:30–11:50', duration: '20 dk', type: 'konusma', typeLabel: 'Bildiri (Sunum)',
    title: 'Bildiri Sunumu', location: 'Salon 1', desc: 'Bildiri sunumu — konuşmacı belirlenecek',
  },
  {
    id: 'g3b-8', time: '12:00–12:20', duration: '20 dk', type: 'konusma', typeLabel: 'Bildiri (Sunum)',
    title: 'Bildiri Sunumu', location: 'Salon 1', desc: 'Bildiri sunumu — konuşmacı belirlenecek',
  },
  {
    id: 'g3b-9', time: '12:20–12:30', duration: '10 dk', type: 'konusma', typeLabel: 'Değerlendirme',
    title: 'Değerlendirme', location: 'Salon 1',
  },
  {
    id: 'g3b-10', time: '12:30–13:30', duration: '60 dk', type: 'arasol', typeLabel: 'Öğle Arası',
    title: 'Öğle Arası', location: 'Yemekhane',
  },
  {
    id: 'g3b-11', time: '13:30–13:50', duration: '20 dk', type: 'konusma', typeLabel: 'Bildiri (Sunum)',
    title: 'Bildiri Sunumu', location: 'Salon 1', desc: 'Bildiri sunumu — konuşmacı belirlenecek',
  },
  {
    id: 'g3b-12', time: '14:00–14:20', duration: '20 dk', type: 'konusma', typeLabel: 'Bildiri (Sunum)',
    title: 'Bildiri Sunumu', location: 'Salon 1', desc: 'Bildiri sunumu — konuşmacı belirlenecek',
  },
  {
    id: 'g3b-13', time: '14:30–14:50', duration: '20 dk', type: 'konusma', typeLabel: 'Bildiri (Sunum)',
    title: 'Bildiri Sunumu', location: 'Salon 1', desc: 'Bildiri sunumu — konuşmacı belirlenecek',
  },
  {
    id: 'g3b-14', time: '15:00–15:20', duration: '20 dk', type: 'konusma', typeLabel: 'Bildiri (Sunum)',
    title: 'Bildiri Sunumu', location: 'Salon 1', desc: 'Bildiri sunumu — konuşmacı belirlenecek',
  },
  {
    id: 'g3b-15', time: '15:30–15:50', duration: '20 dk', type: 'konusma', typeLabel: 'Bildiri (Sunum)',
    title: 'Bildiri Sunumu', location: 'Salon 1', desc: 'Bildiri sunumu — konuşmacı belirlenecek',
  },
  {
    id: 'g3b-16', time: '16:00–16:20', duration: '20 dk', type: 'konusma', typeLabel: 'Bildiri (Sunum)',
    title: 'Bildiri Sunumu', location: 'Salon 1', desc: 'Bildiri sunumu — konuşmacı belirlenecek',
  },
  {
    id: 'g3b-17', time: '16:30–16:50', duration: '20 dk', type: 'konusma', typeLabel: 'Bildiri (Sunum)',
    title: 'Bildiri Sunumu', location: 'Salon 1', desc: 'Bildiri sunumu — konuşmacı belirlenecek',
  },
  {
    id: 'g3b-18', time: '16:50–17:00', duration: '10 dk', type: 'opening', typeLabel: 'Kapanış',
    title: 'Kapanış', location: 'Salon 1',
  },
];

// ════════════════════════════════════════════════════
//  3. GÜN — Poster Sunumları & Kapanış (Konferans Salonu)
// ════════════════════════════════════════════════════

export const GUN3 = [
  {
    id: 'g3-1',
    time: '08:30–09:00',
    duration: '30 dk',
    type: 'arasol',
    typeLabel: 'Lojistik',
    title: 'Hazırlık & Teknik Kontrol',
    location: 'Konferans Salonu',
    desc: 'Sunum salonlarının teknik kurulumu ve proje gruplarının son hazırlıkları',
  },
  {
    id: 'g3-2',
    time: '09:00–09:15',
    duration: '15 dk',
    type: 'opening',
    typeLabel: 'Açılış',
    title: '3. Gün Açılış',
    location: 'Konferans Salonu',
    desc: 'Sunum gününe genel bakış ve jüri tanıtımı',
    speaker: 'Organizasyon Komitesi',
  },
  {
    id: 'g3-3',
    time: '09:15–12:30',
    duration: '195 dk',
    type: 'konusma',
    typeLabel: 'Poster Sunumları',
    title: 'Poster Sunumları',
    location: 'Konferans Salonu',
    desc: 'Her salondan proje grupları jüri önünde sunum yapar (5–7 dk / grup)',
    speaker: 'Jüri',
    highlight: true,
  },
  {
    id: 'g3-4',
    time: '12:30–13:30',
    duration: '60 dk',
    type: 'arasol',
    typeLabel: 'Mola',
    title: 'Öğle Yemeği',
    location: 'Yemekhane',
  },
  {
    id: 'g3-5',
    time: '13:30–15:30',
    duration: '120 dk',
    type: 'konusma',
    typeLabel: 'Poster Sunumları',
    title: 'Poster Sunumları (Devam)',
    location: 'Konferans Salonu',
    desc: 'Her salondan proje grupları jüri önünde sunum yapar (5–7 dk / grup)',
    speaker: 'Jüri',
    highlight: true,
  },
  {
    id: 'g3-6',
    time: '15:30–16:00',
    duration: '30 dk',
    type: 'arasol',
    typeLabel: 'Ara',
    title: 'Mola & Jüri Değerlendirme Süreci',
  },
  {
    id: 'g3-7',
    time: '16:00–16:45',
    duration: '45 dk',
    type: 'opening',
    typeLabel: 'Ödül Töreni',
    title: 'Ödül Töreni',
    location: 'Konferans Salonu',
    desc: 'En iyi 3 projeye teşvik ödülü, tüm katılımcılara Katılım Belgesi dağıtımı',
    speaker: 'Jüri + Organizasyon Komitesi',
    highlight: true,
  },
  {
    id: 'g3-8',
    time: '16:45–17:00',
    duration: '15 dk',
    type: 'opening',
    typeLabel: 'Kapanış',
    title: 'Kapanış Töreni',
    location: 'Konferans Salonu',
    desc: 'Etkinlik değerlendirmesi, teşekkür ve kapanış konuşmaları',
    speaker: 'MYO Müdürü / Dr. Öğr. Üyesi Şaban Fındık',
    highlight: true,
  },
];