// ════════════════════════════════════════════════════
//  PROGRAM VERİSİ — Mucur Yapay Zeka Günleri
//  Kırşehir Ahi Evran Üniversitesi · Mucur MYO
// ════════════════════════════════════════════════════

export const GUN1 = [
  {
    id: 'g1-1',
    time: '08:30–09:00',
    duration: '30 dk',
    type: 'arasol',
    typeLabel: 'Lojistik',
    title: 'Kayıt ve Karşılama',
    location: 'Giriş Holü',
    desc: 'Katılımcı kaydı, isim kartı ve doküman dağıtımı',
  },
  {
    id: 'g1-2',
    time: '09:00–09:30',
    duration: '30 dk',
    type: 'opening',
    typeLabel: 'Tören',
    title: 'Açılış Töreni',
    location: 'Konferans Salonu',
    desc: 'İstiklal Marşı, saygı duruşu, protokol fotoğrafı',
    highlight: true,
  },
  {
    id: 'g1-3',
    time: '09:30–10:00',
    duration: '30 dk',
    type: 'konusma',
    typeLabel: 'Konuşma',
    title: 'Rektör / Rektör Yrd. Açılış Konuşması',
    location: 'Konferans Salonu',
    desc: 'YZ ve mesleki eğitimde Kırşehir Ahi Evran Üniversitesi\'nin vizyonu',
    speaker: 'Rektörlük — Kırşehir Ahi Evran Üniversitesi',
    highlight: true,
  },
  {
    id: 'g1-4',
    time: '10:00–10:20',
    duration: '20 dk',
    type: 'konusma',
    typeLabel: 'Konuşma',
    title: 'MYO Müdürü Konuşması',
    location: 'Konferans Salonu',
    desc: 'Mucur MYO\'nun 9 bölüm bazında YZ stratejisi',
    speaker: 'MYO Müdürü — Mucur Meslek Yüksekokulu',
  },
  {
    id: 'g1-5',
    time: '10:20–10:40',
    duration: '20 dk',
    type: 'konusma',
    typeLabel: 'Paydaş Konuşması',
    title: 'İlçe Kaymakamı Konuşması',
    location: 'Konferans Salonu',
    desc: 'Bölgesel kalkınmada ve Mucur ilçesinin geleceğinde yapay zekanın rolü',
    speaker: 'Kaymakam — Mucur Kaymakamlığı, Kırşehir',
    highlight: true,
  },
  {
    id: 'g1-6',
    time: '10:40–11:00',
    duration: '20 dk',
    type: 'arasol',
    typeLabel: 'Ara',
    title: 'Kahve Molası ve Networking',
    location: 'Fuaye',
  },
  {
    id: 'g1-7',
    time: '11:00–11:45',
    duration: '45 dk',
    type: 'konusma',
    typeLabel: 'Sektör Sunumu',
    title: 'Sektör Sunumu 1 — Sanayi / Üretim',
    location: 'Konferans Salonu',
    desc: 'Kimya, makine ve üretim sektöründe YZ uygulamaları ve eleman talepleri',
    speaker: 'Sanayi Temsilcisi',
  },
  {
    id: 'g1-8',
    time: '11:45–12:30',
    duration: '45 dk',
    type: 'konusma',
    typeLabel: 'Sektör Sunumu',
    title: 'Sektör Sunumu 2 — Lojistik / Ulaşım',
    location: 'Konferans Salonu',
    desc: 'Taşımacılık, posta ve lojistik sektöründe YZ ve otomasyon',
    speaker: 'Lojistik Sektörü Temsilcisi',
  },
  {
    id: 'g1-9',
    time: '12:30–13:30',
    duration: '60 dk',
    type: 'arasol',
    typeLabel: 'Mola',
    title: 'Öğle Yemeği',
    location: 'Yemekhane',
  },
  {
    id: 'g1-10',
    time: '13:30–14:15',
    duration: '45 dk',
    type: 'konusma',
    typeLabel: 'Sektör Sunumu',
    title: 'Sektör Sunumu 3 — Finans / Bankacılık',
    location: 'Konferans Salonu',
    desc: 'Kredi, risk, sigorta ve dijital bankacılıkta YZ yenilikleri',
    speaker: 'Finans Sektörü Temsilcisi',
  },
  {
    id: 'g1-11',
    time: '14:15–15:00',
    duration: '45 dk',
    type: 'konusma',
    typeLabel: 'Sektör Sunumu',
    title: 'Sektör Sunumu 4 — Medya / Tasarım / BT',
    location: 'Konferans Salonu',
    desc: 'Grafik, oyun, yazılım ve medya sektöründe YZ araçları ve istihdam',
    speaker: 'Dijital Sektör Temsilcisi',
  },
  {
    id: 'g1-12',
    time: '15:00–15:15',
    duration: '15 dk',
    type: 'arasol',
    typeLabel: 'Kısa Mola',
    title: 'Mola',
  },
  {
    id: 'g1-13',
    time: '15:15–16:30',
    duration: '75 dk',
    type: 'panel',
    typeLabel: 'Panel',
    title: 'Panel: Sektörün YZ Talepleri ve Meslekî Yeterlilik',
    location: 'Konferans Salonu',
    desc: 'Mucur MYO 9 bölümünden sektörlere yönelik işgücü beklentileri; moderatörlü tartışma',
    speaker: 'Panel Konuşmacıları + Moderatör',
    highlight: true,
  },
  {
    id: 'g1-14',
    time: '16:30–17:00',
    duration: '30 dk',
    type: 'konusma',
    typeLabel: 'Değerlendirme',
    title: 'Gün Sonu Değerlendirme',
    location: 'Konferans Salonu',
    desc: 'Gün özeti ve yarınki workshop yönlendirmesi',
    speaker: 'MYO Müdürü',
  },
];

export const GUN2 = [
  {
    id: 'g2-1',
    time: '09:00–09:20',
    duration: '20 dk',
    type: 'opening',
    typeLabel: 'Bilgilendirme',
    title: 'Gün Açılışı ve Workshop Yönlendirme',
    location: 'Konferans Salonu',
    desc: '9 bölüm için salon atamaları ve rehber bilgi',
    speaker: 'Organizasyon Sorumlusu',
  },
  {
    id: 'g2-2',
    time: '09:20–09:50',
    duration: '30 dk',
    type: 'konusma',
    typeLabel: 'Anahtar Konuşma',
    title: 'Davetli Konuşmacı: Türkiye\'de YZ Ekosistemi',
    location: 'Konferans Salonu',
    desc: 'Güncel YZ modelleri, sektörel dönüşüm ve kariyer rehberliği',
    speaker: 'Davetli Akademisyen / Sektör Uzmanı',
    highlight: true,
  },
  {
    id: 'g2-3',
    time: '09:50–10:00',
    duration: '10 dk',
    type: 'arasol',
    typeLabel: 'Lojistik',
    title: 'Salon Geçişleri',
    location: 'Tüm Salon / Lab',
    desc: 'Workshop salonlarına ve laboratuvarlara yönlendirme',
  },
  {
    id: 'g2-4',
    time: '10:00–12:00',
    duration: '120 dk',
    type: 'workshop',
    typeLabel: 'Workshop Bloku 1',
    title: 'WS Bloku 1 — Bölüm Bazlı Paralel Seanslar',
    location: 'Salon A–J',
    desc: '9 bölüm workshop\'u eş zamanlı; her bölüm kendi salonunda çalışır.',
    highlight: true,
  },
  {
    id: 'g2-5',
    time: '12:00–13:00',
    duration: '60 dk',
    type: 'arasol',
    typeLabel: 'Mola',
    title: 'Öğle Yemeği',
    location: 'Yemekhane',
  },
  {
    id: 'g2-6',
    time: '13:00–15:00',
    duration: '120 dk',
    type: 'workshop',
    typeLabel: 'Workshop Bloku 2',
    title: 'WS Bloku 2 — Bölüm Bazlı Paralel Seanslar (Devam)',
    location: 'Salon A–J',
    desc: '9 bölüm workshop\'u devamı; proje geliştirme ve çıktı üretimi.',
    highlight: true,
  },
  {
    id: 'g2-7',
    time: '15:00–15:20',
    duration: '20 dk',
    type: 'arasol',
    typeLabel: 'Mola',
    title: 'Mola',
    location: 'Fuaye',
  },
  {
    id: 'g2-8',
    time: '15:20–16:30',
    duration: '70 dk',
    type: 'workshop',
    typeLabel: 'Açık Seans',
    title: 'WS Bloku 3 — Açık Seans (Salon K)',
    location: 'Salon K',
    desc: 'Tüm dışarıdan katılımcılara açık temel YZ araçları workshop\'u. ChatGPT, Gemini, Microsoft Copilot uygulamalı kullanım. Max. 30 kişi · Ön kayıt zorunlu.',
    speaker: 'Gönüllü Öğr. Elemanı',
    highlight: true,
  },
  {
    id: 'g2-9',
    time: '16:30–17:00',
    duration: '30 dk',
    type: 'panel',
    typeLabel: 'Paylaşım',
    title: 'Workshop Çıktıları — Bölümlerarası Paylaşım',
    location: 'Konferans Salonu',
    desc: 'Her bölümden workshop çıktısı özet sunumu (3–5 dk/bölüm)',
    speaker: 'Düzenleme Kurulu',
  },
];

export const GUN3 = [
  {
    id: 'g3-1',
    time: '09:00–09:20',
    duration: '20 dk',
    type: 'opening',
    typeLabel: 'Bilgilendirme',
    title: 'Son Gün Açılışı ve Program Duyurusu',
    location: 'Konferans Salonu',
    desc: 'Sunum takvimi ve jüri tanıtımı',
    speaker: 'Organizasyon Sorumlusu',
  },
  {
    id: 'g3-2',
    time: '09:20–11:00',
    duration: '100 dk',
    type: 'konusma',
    typeLabel: 'Proje Sunumu',
    title: 'Öğrenci / Grup Proje Sunumları — 1. Tur',
    location: 'Konferans Salonu',
    desc: 'Workshop çıktısı projelerin jüri önünde sunumu — Bölümler 1–5 (Bilgisayar Tekn., Kimya, Güvenlik, Finans, Tasarım)',
    speaker: 'Jüri',
    highlight: true,
  },
  {
    id: 'g3-3',
    time: '11:00–11:15',
    duration: '15 dk',
    type: 'arasol',
    typeLabel: 'Mola',
    title: 'Mola',
  },
  {
    id: 'g3-4',
    time: '11:15–12:30',
    duration: '75 dk',
    type: 'konusma',
    typeLabel: 'Proje Sunumu',
    title: 'Öğrenci / Grup Proje Sunumları — 2. Tur',
    location: 'Konferans Salonu',
    desc: 'Workshop çıktısı projelerin jüri önünde sunumu — Bölümler 6–9 (Ulaştırma, Medya, Yönetim, Yazılım)',
    speaker: 'Jüri',
    highlight: true,
  },
  {
    id: 'g3-5',
    time: '12:30–13:30',
    duration: '60 dk',
    type: 'arasol',
    typeLabel: 'Mola',
    title: 'Öğle Yemeği',
    location: 'Yemekhane',
  },
  {
    id: 'g3-6',
    time: '13:30–14:30',
    duration: '60 dk',
    type: 'konusma',
    typeLabel: 'Anahtar Konuşma',
    title: 'Davetli Konuşmacı: YZ\'nin Geleceği ve Kariyer',
    location: 'Konferans Salonu',
    desc: 'Öğrenciler için YZ kariyer rehberliği; sektörel öneri ve yol haritası',
    speaker: 'Davetli Uzman',
    highlight: true,
  },
  {
    id: 'g3-7',
    time: '14:30–15:00',
    duration: '30 dk',
    type: 'panel',
    typeLabel: 'Değerlendirme',
    title: 'Jüri Değerlendirme ve Ödül Açıklaması',
    location: 'Konferans Salonu',
    desc: 'En iyi proje ve workshop çıktısı seçimi; teşvik ödülleri takdimi',
    speaker: 'Jüri Başkanı',
    highlight: true,
  },
  {
    id: 'g3-8',
    time: '15:00–15:20',
    duration: '20 dk',
    type: 'konusma',
    typeLabel: 'Rapor Sunumu',
    title: 'Etik Kurulu + Düzenleme Kurulu Önerileri',
    location: 'Konferans Salonu',
    desc: 'Çalıştay etik raporu ve düzenleme kurulu önerileri',
    speaker: 'Kurul Başkanları',
  },
  {
    id: 'g3-9',
    time: '15:20–15:30',
    duration: '10 dk',
    type: 'arasol',
    typeLabel: 'Kısa Mola',
    title: 'Mola',
  },
  {
    id: 'g3-10',
    time: '15:30–16:00',
    duration: '30 dk',
    type: 'opening',
    typeLabel: 'Kapanış Töreni',
    title: 'Kapanış Töreni ve Teşekkür',
    location: 'Konferans Salonu',
    desc: 'Katkı belgesi takdimi, teşekkür konuşmaları ve kapanış',
    speaker: 'MYO Müdürü + Protokol',
    highlight: true,
  },
];