export const programSessions = [
  {
    id: 1,
    time: "09:00 – 10:00",
    duration: "60 dk",
    title: "Kayıt ve Karşılama",
    description: "Konukların kabulü ve networking başlangıcı",
    location: "Ana Fuaye",
    type: "break",
    speaker: null,
  },
  {
    id: 2,
    time: "10:00 – 10:45",
    duration: "45 dk",
    title: "Açılış Konuşması",
    description: "Yapay Zeka ve Geleceğin Vizyonu üzerine ana tema konuşması",
    location: "Salon A",
    type: "keynote",
    speaker: "Dr. Ahmet Yusuf",
  },
  {
    id: 3,
    time: "11:00 – 12:30",
    duration: "90 dk",
    title: "Panel: Sektörel Dönüşüm",
    description: "Endüstri 5.0 ve AI entegrasyonu üzerine uzman paneli",
    location: "Salon A",
    type: "panel",
    speaker: "Prof. Elif Deniz, Caner Kaya",
  },
  {
    id: 4,
    time: "12:30 – 13:30",
    duration: "60 dk",
    title: "Öğle Arası",
    description: "Networking ve yemek arası",
    location: "Yemek Alanı",
    type: "break",
    speaker: null,
  },
  {
    id: 5,
    time: "14:00 – 15:00",
    duration: "60 dk",
    title: "Eğitimde AI Dönüşümü",
    description: "Müfredatta yapay zeka entegrasyonu ve dijital okuryazarlık",
    location: "Salon B",
    type: "keynote",
    speaker: "Zeynep Şahin",
  },
  {
    id: 6,
    time: "15:00 – 15:30",
    duration: "30 dk",
    title: "Çay Arası",
    description: "Kısa mola ve networking",
    location: "Fuaye",
    type: "break",
    speaker: null,
  },
  {
    id: 7,
    time: "15:30 – 17:00",
    duration: "90 dk",
    title: "Workshop: Uygulamalı AI",
    description: "TensorFlow ile Görüntü İşleme Temelleri üzerine uygulamalı atölye",
    location: "Lab 1",
    type: "workshop",
    speaker: "Caner Kaya",
  },
  {
    id: 8,
    time: "17:00 – 17:30",
    duration: "30 dk",
    title: "Kapanış ve Sertifika Töreni",
    description: "Etkinlik değerlendirmesi ve katılım sertifikası dağıtımı",
    location: "Salon A",
    type: "keynote",
    speaker: "Dr. Ahmet Yusuf",
  },
];

export const programTypes = [
  { value: "all", label: "Tümü" },
  { value: "keynote", label: "Konuşma" },
  { value: "panel", label: "Panel" },
  { value: "workshop", label: "Workshop" },
  { value: "break", label: "Mola" },
];