export const speakers = [
  {
    id: 1,
    name: "Dr. Öğr. Üyesi Şaban Fındık",
    role: "Bölüm Başkanı",
    org: "Mucur Meslek Yüksekokulu",
    bio: "Bilgisayar Teknolojileri Bölümü. Yapay zeka odaklı müfredat geliştirme süreçlerini yönetmektedir.",
    topics: ["Bilgisayar Teknolojileri", "Yazılım Geliştirme"],
  },
  {
    id: 2,
    name: "Prof. Dr. Mustafa Kasım Karahocagil",
    role: "Rektör",
    org: "Kırşehir Ahi Evran Üniversitesi",
    bio: "Üniversitenin akademik vizyonunu yapay zeka ve dijital dönüşüm ekseninde şekillendirmektedir.",
    topics: ["Akademik Vizyon", "Dijital Dönüşüm"],
  },
  {
    id: 3,
    name: "Prof. Dr. Murat Çanlı",
    role: "MYO Müdürü",
    org: "Mucur Meslek Yüksekokulu",
    bio: "Mesleki eğitimde yapay zeka entegrasyonuna liderlik etmektedir.",
    topics: ["Mesleki Eğitim", "Stratejik Yönetim"],
  },
  {
    id: 4,
    name: "Doç. Dr. Yusuf Ziya Olpak",
    role: "Rektör Yardımcısı",
    org: "Kırşehir Ahi Evran Üniversitesi",
    bio: "Yapay zeka ve eğitim teknolojileri alanında çalışmalar yürütmektedir.",
    topics: ["Yapay Zeka", "Eğitim Teknolojileri"],
  },
  {
    id: 5,
    name: "Emre Yeşilbaş",
    role: "İlçe Kaymakamı",
    org: "Mucur Kaymakamlığı, Kırşehir",
    bio: "Bölgesel kalkınma projelerinde aktif rol almakta, yapay zekanın kamu hizmetlerindeki potansiyeline destek vermektedir.",
    topics: ["Bölgesel Kalkınma", "Kamu Yönetimi"],
  },
  {
    id: 6,
    name: "Hasan Hüseyin Erden",
    role: "Kurucu",
    org: "Marta Teknoloji",
    bio: "Teknoloji girişimcisi olarak yapay zeka destekli çözümler geliştirmekte ve sektöre yön vermektedir.",
    topics: ["Teknoloji Girişimciliği", "Yapay Zeka"],
  },
  {
    id: 7,
    name: "Orsan Pınar",
    role: "İlçe Milli Eğitim Müdürü",
    org: "Mucur İlçe Milli Eğitim Müdürlüğü",
    bio: "Mucur ilçesinde eğitim teknolojilerinin yaygınlaştırılması ve yapay zeka okuryazarlığının geliştirilmesi için çalışmalar yürütmektedir.",
    topics: ["Eğitim Yönetimi", "Eğitim Teknolojileri"],
  },
  {
    id: 8,
    name: "Sercan Reyhanlı",
    role: "Developer",
    org: "Google Developer Teamfly",
    bio: "Google geliştirici ekosisteminde aktif rol alarak yapay zeka araçlarının yazılım geliştirme süreçlerine entegrasyonuna öncülük etmektedir.",
    topics: ["Yazılım Geliştirme", "Google Teknolojileri"],
  },
];