export const speakers = [
  {
    id: 1,
    name: "Dr. Öğr. Üyesi Şaban Fındık",
    role: "Bilgisayar Teknolojileri Bölüm Başkanı",
    org: "Mucur Meslek Yüksekokulu",
    bio: "Bilgisayar teknolojileri alanında akademik çalışmalarını sürdürmekte, bölümün yapay zeka odaklı müfredat geliştirme süreçlerini yönetmektedir.",
    topics: ["Bilgisayar Teknolojileri", "Yazılım Geliştirme"],
  },
  {
    id: 2,
    name: "Prof. Dr. Mustafa Kasım Karahocagil",
    role: "Rektör",
    org: "Kırşehir Ahi Evran Üniversitesi",
    bio: "Kırşehir Ahi Evran Üniversitesi Rektörü. Üniversitenin akademik vizyonunu yapay zeka ve dijital dönüşüm ekseninde şekillendirmektedir.",
    topics: ["Akademik Vizyon", "Dijital Dönüşüm"],
  },
  {
    id: 3,
    name: "Prof. Dr. Murat Çanlı",
    role: "Müdür",
    org: "Mucur Meslek Yüksekokulu",
    bio: "Mucur MYO Müdürü olarak yüksekokulun stratejik yönetimini üstlenmekte, mesleki eğitimde yapay zeka entegrasyonuna liderlik etmektedir.",
    topics: ["Mesleki Eğitim", "Stratejik Yönetim"],
  },
  {
    id: 4,
    name: "Doç. Dr. Yusuf Ziya Olpak",
    role: "Yapay Zeka Yardımcısı",
    org: "Kırşehir Ahi Evran Üniversitesi",
    bio: "Yapay zeka ve eğitim teknolojileri alanında akademik çalışmalar yürütmekte, çalıştayın bilimsel koordinasyonunda aktif rol almaktadır.",
    topics: ["Yapay Zeka", "Eğitim Teknolojileri"],
  },
  {
    id: 5,
    name: "Emre Yeşilbaş",
    role: "Kaymakam",
    org: "Mucur Kaymakamlığı",
    bio: "Mucur İlçe Kaymakamı olarak bölgesel kalkınma projelerinde aktif rol almakta, yapay zekanın kamu hizmetlerindeki potansiyeline destek vermektedir.",
    topics: ["Bölgesel Kalkınma", "Kamu Yönetimi"],
  },
];