export const speakers = [
  {
    id: 1,
    name: "Dr. Öğr. Üyesi Şaban Fındık",
    role: "Bölüm Başkanı",
    org: "Mucur Meslek Yüksekokulu",
    bio: "Bilgisayar Teknolojileri Bölümü. Yapay zeka odaklı müfredat geliştirme süreçlerini yönetmektedir.",
    topics: ["Bilgisayar Teknolojileri", "Yazılım Geliştirme"],
  },
  {
    id: 2,
    name: "Prof. Dr. Mustafa Kasım Karahocagil",
    role: "Rektör",
    org: "Kırşehir Ahi Evran Üniversitesi",
    bio: "Üniversitenin akademik vizyonunu yapay zeka ve dijital dönüşüm ekseninde şekillendirmektedir.",
    topics: ["Akademik Vizyon", "Dijital Dönüşüm"],
  },
  {
    id: 3,
    name: "Prof. Dr. Murat Çanlı",
    role: "MYO Müdürü",
    org: "Mucur Meslek Yüksekokulu",
    bio: "Mesleki eğitimde yapay zeka entegrasyonuna liderlik etmektedir.",
    topics: ["Mesleki Eğitim", "Stratejik Yönetim"],
  },
  {
    id: 4,
    name: "Doç. Dr. Yusuf Ziya Olpak",
    role: "Rektör Yardımcısı",
    org: "Kırşehir Ahi Evran Üniversitesi",
    bio: "Yapay zeka ve eğitim teknolojileri alanında çalışmalar yürütmektedir.",
    topics: ["Yapay Zeka", "Eğitim Teknolojileri"],
  },
  {
    id: 5,
    name: "Emre Yeşilbaş",
    role: "İlçe Kaymakamı",
    org: "Mucur Kaymakamlığı, Kırşehir",
    bio: "Bölgesel kalkınma projelerinde aktif rol almakta, yapay zekanın kamu hizmetlerindeki potansiyeline destek vermektedir.",
    topics: ["Bölgesel Kalkınma", "Kamu Yönetimi"],
  },

  {
    id: 7,
    name: "Orsan Pınar",
    role: "İlçe Milli Eğitim Müdürü",
    org: "Mucur İlçe Milli Eğitim Müdürlüğü",
    bio: "Mucur ilçesinde eğitim teknolojilerinin yaygınlaştırılması ve yapay zeka okuryazarlığının geliştirilmesi için çalışmalar yürütmektedir.",
    topics: ["Eğitim Yönetimi", "Eğitim Teknolojileri"],
  },

  {
    id: 9,
    name: "Prof. Dr. Süleyman Ersöz",
    role: "Mühendislik Fakültesi",
    org: "Kırıkkale Üniversitesi",
    bio: "Kırıkkale Üniversitesi Mühendislik Fakültesi'nde görev yapmaktadır. Endüstriyel mühendislik ve yapay zeka uygulamaları alanında akademik çalışmalar yürütmektedir.",
    topics: ["Endüstri Mühendisliği", "Yapay Zeka Uygulamaları"],
  },
  {
    id: 10,
    name: "BTK Akademi Temsilcisi",
    role: "Eğitim ve Teknoloji Uzmanı",
    org: "BTK Akademi",
    bio: "Türkiye'nin dijital dönüşümüne katkı sağlayan BTK Akademi bünyesinde yapay zeka ve teknoloji alanında eğitim programları yürütmektedir.",
    topics: ["Dijital Eğitim", "Yapay Zeka Eğitimi"],
  },
  {
    id: 11,
    name: "Petlas CEO",
    role: "CEO",
    org: "Petlas",
    bio: "Türkiye'nin önde gelen lastik üreticisi Petlas'ın genel müdürü olarak sanayi sektöründe yapay zeka ve otomasyon uygulamalarına liderlik etmektedir.",
    topics: ["Sanayi", "Endüstriyel Otomasyon"],
  },
  {
    id: 12,
    name: "Çamaş Genel Müdürü",
    role: "Genel Müdür",
    org: "Çamaş",
    bio: "Çamaş firmasının genel müdürü olarak üretim ve lojistik süreçlerinde dijital dönüşüm ve yapay zeka projelerini yönetmektedir.",
    topics: ["Üretim Yönetimi", "Dijital Dönüşüm"],
  },
];